version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./static/plots:/app/static/plots
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
